# Generated by Django 3.2.4 on 2021-10-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100, null=True)),
                ('component', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('handle', models.CharField(max_length=50, null=True, unique=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('prompt', models.CharField(max_length=300, null=True)),
                ('prompt_fr', models.CharField(max_length=300, null=True)),
                ('prompt_en', models.CharField(max_length=300, null=True)),
                ('reverse', models.BooleanField(blank=True, null=True)),
                ('min_val', models.IntegerField(blank=True, null=True)),
                ('max_val', models.IntegerField(blank=True, null=True)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('annotations', models.CharField(max_length=200, null=True)),
                ('annotations_fr', models.CharField(max_length=200, null=True)),
                ('annotations_en', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('widget', models.CharField(max_length=30, null=True)),
                ('help_text', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text_en', models.CharField(blank=True, max_length=200, null=True)),
                ('validate', models.CharField(blank=True, default='', max_length=200)),
                ('initial', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.participantprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='survey_app.question')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager_app.experimentsession')),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.study')),
            ],
        ),
    ]
